Algoritmo "primeiro"
// Disciplina   : Lógica e Interpretação de Dados
// Professor   : Arthur Mariano L NETO 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/02/2023
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

   escreva("Olá Mundo!")

Fimalgoritmo